package compiler

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// TranspileDir recursively finds .gox files and transpiles them to .gox.go
func TranspileDir(dir string) error {
	return filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".gox") {
			return TranspileFile(path)
		}
		return nil
	})
}

// TranspileFile transpiles a single .gox file into a .gox.go file
func TranspileFile(goxPath string) error {
	content, err := os.ReadFile(goxPath)
	if err != nil {
		return err
	}

	transpiled, err := Transpile(string(content))
	if err != nil {
		return fmt.Errorf("failed to transpile %s: %w", goxPath, err)
	}

	outPath := strings.TrimSuffix(goxPath, ".gox") + ".go"
	header := "// Code generated by GoKS GOX compiler. DO NOT EDIT.\n"
	return os.WriteFile(outPath, []byte(header+transpiled), 0644)
}

// Transpile converts a .gox string to valid Go component syntax.
func Transpile(content string) (string, error) {
	// Find all `return (` ... `)` blocks
	idx := 0
	for {
		start := strings.Index(content[idx:], "return (")
		if start == -1 {
			break
		}
		start += idx

		// Find matching parenthesis
		openCount := 1
		end := start + 8 // length of "return ("
		for end < len(content) {
			if content[end] == '(' {
				openCount++
			} else if content[end] == ')' {
				openCount--
				if openCount == 0 {
					break
				}
			}
			end++
		}

		if openCount != 0 || end >= len(content) {
			idx = start + 8
			continue
		}

		xmlContent := strings.TrimSpace(content[start+8 : end])

		// Parse XML
		transpiledXML, err := parseXMLToGo(xmlContent)
		if err != nil {
			return "", fmt.Errorf("failed to parse XML: %v\nContent: %s", err, xmlContent)
		}

		// Replace in content
		prefix := content[:start]
		suffix := content[end+1:]

		replacement := "return " + transpiledXML
		content = prefix + replacement + suffix
		idx = len(prefix) + len(replacement)
	}

	return content, nil
}

func parseXMLToGo(xmlStr string) (string, error) {
	if xmlStr == "" {
		return "", nil
	}

	d := xml.NewDecoder(strings.NewReader(xmlStr))
	// Allow unescaped HTML characters and unknown entities
	d.Strict = false
	d.AutoClose = xml.HTMLAutoClose
	d.Entity = xml.HTMLEntity

	return parseNode(d)
}

func parseNode(d *xml.Decoder) (string, error) {
	var children []string

	for {
		t, err := d.Token()
		if err != nil {
			if err.Error() == "EOF" {
				break
			}
			return "", err
		}

		switch token := t.(type) {
		case xml.StartElement:
			tag := token.Name.Local

			// Extract namespace if any (e.g. c.Hero -> Space: c, Local: Hero)
			if token.Name.Space != "" {
				tag = token.Name.Space + "." + token.Name.Local
			}

			// Parse children recursively
			inner, err := parseNode(d)
			if err != nil {
				return "", err
			}

			goCode := formatGoNode(tag, token.Attr, inner)
			children = append(children, goCode)

		case xml.EndElement:
			return strings.Join(children, ", "), nil

		case xml.CharData:
			text := strings.TrimSpace(string(token))
			if text != "" {
				if strings.HasPrefix(text, "{") && strings.HasSuffix(text, "}") {
					expr := text[1 : len(text)-1]
					children = append(children, fmt.Sprintf("component.Any(%s)", expr))
				} else {
					children = append(children, fmt.Sprintf("%q", text))
				}
			}
		}
	}

	return strings.Join(children, ", "), nil
}

func formatGoNode(tag string, attrs []xml.Attr, inner string) string {
	isComponent := strings.Contains(tag, ".")

	var goTag string
	if isComponent {
		goTag = tag // e.g. c.Hero
	} else {
		goTag = "html." + strings.ToUpper(tag[0:1]) + tag[1:]
	}

	var res string
	if isComponent {
		// Component instantiation: component.C(&c.Hero{Attr1: "val", ...})
		props := []string{}
		for _, a := range attrs {
			val := a.Value
			// if value is {expr}, don't quote it
			if strings.HasPrefix(val, "{") && strings.HasSuffix(val, "}") {
				props = append(props, fmt.Sprintf("%s: %s", a.Name.Local, val[1:len(val)-1]))
			} else {
				props = append(props, fmt.Sprintf("%s: %q", a.Name.Local, val))
			}
		}
		res = fmt.Sprintf("component.C(&%s{%s})", goTag, strings.Join(props, ", "))
	} else {
		// HTML Element: html.Div(inner)
		res = fmt.Sprintf("%s(%s)", goTag, inner)

		for _, a := range attrs {
			name := a.Name.Local
			val := a.Value

			if name == "class" {
				if strings.HasPrefix(val, "{") && strings.HasSuffix(val, "}") {
					res += fmt.Sprintf(`.Class(%s)`, val[1:len(val)-1])
				} else {
					res += fmt.Sprintf(`.Class(%q)`, val)
				}
			} else if name == "id" {
				if strings.HasPrefix(val, "{") && strings.HasSuffix(val, "}") {
					res += fmt.Sprintf(`.ID(%s)`, val[1:len(val)-1])
				} else {
					res += fmt.Sprintf(`.ID(%q)`, val)
				}
			} else {
				if strings.HasPrefix(val, "{") && strings.HasSuffix(val, "}") {
					res += fmt.Sprintf(`.Attr(%q, %s)`, name, val[1:len(val)-1])
				} else {
					res += fmt.Sprintf(`.Attr(%q, %q)`, name, val)
				}
			}
		}
	}

	return res
}
