package compiler

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// PrepareWorkspace mirrors user code to .goks/workspace, transpiling .gox files to .go
// and cleaning up any generated .go files in the source app directory.
func PrepareWorkspace(appDir string) error {
	workspaceDir := filepath.Join(appDir, ".goks", "workspace")
	_ = os.RemoveAll(workspaceDir)
	if err := os.MkdirAll(workspaceDir, 0755); err != nil {
		return err
	}

	return filepath.Walk(appDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(appDir, path)
		if err != nil {
			return err
		}

		if rel == "." {
			return nil
		}

		// Skip hidden and build directories
		base := info.Name()
		if info.IsDir() && (base == ".goks" || base == ".git" || base == "node_modules" || base == "vendor") {
			return filepath.SkipDir
		}

		if strings.HasPrefix(rel, ".goks") || strings.HasPrefix(rel, ".git") || strings.HasPrefix(rel, "node_modules") {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		destPath := filepath.Join(workspaceDir, NormalizeWorkspaceRel(rel))

		if info.IsDir() {
			return os.MkdirAll(destPath, 0755)
		}

		// If it's a .gox file: transpile to .go inside workspace
		if strings.HasSuffix(path, ".gox") {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			transpiled, err := Transpile(string(content))
			if err != nil {
				return fmt.Errorf("failed to transpile %s: %w", path, err)
			}
			destFile := strings.TrimSuffix(destPath, ".gox") + ".go"
			header := "// Code generated by GoKS GOX compiler. DO NOT EDIT.\n"
			if err := os.WriteFile(destFile, []byte(header+transpiled), 0644); err != nil {
				return err
			}

			// Clean up any legacy generated .go file in source appDir
			legacyGoFile := strings.TrimSuffix(path, ".gox") + ".go"
			if legData, err := os.ReadFile(legacyGoFile); err == nil {
				if strings.HasPrefix(string(legData), "// Code generated by GoKS GOX compiler") {
					_ = os.Remove(legacyGoFile)
				}
			}
			return nil
		}

		// If it's a legacy generated file in appDir, clean it up!
		if strings.HasSuffix(path, ".go") {
			if legData, err := os.ReadFile(path); err == nil {
				if strings.HasPrefix(string(legData), "// Code generated by GoKS GOX compiler") {
					_ = os.Remove(path)
					return nil
				}
			}
		}

		// Copy non-gox files to workspace (go.mod, regular .go files, etc.)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(destPath, data, info.Mode())
	})
}

// TranspileDir recursively finds .gox files and transpiles them to .gox.go
func TranspileDir(dir string) error {
	return filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".gox") {
			return TranspileFile(path)
		}
		return nil
	})
}

// CompileError represents a compilation error mapped directly to the .gox source file.
type CompileError struct {
	File    string
	Line    int
	Column  int
	Snippet string
	Message string
}

func (e *CompileError) Error() string {
	var sb strings.Builder
	if e.File != "" {
		fmt.Fprintf(&sb, "%s:%d:%d: compile error: %s", e.File, e.Line, e.Column, e.Message)
	} else if e.Line > 0 {
		fmt.Fprintf(&sb, "line %d:%d: compile error: %s", e.Line, e.Column, e.Message)
	} else {
		fmt.Fprintf(&sb, "compile error: %s", e.Message)
	}
	if e.Snippet != "" {
		sb.WriteString("\n" + e.Snippet)
	}
	return sb.String()
}

func createSnippet(content string, line int, col int) string {
	lines := strings.Split(content, "\n")
	if line < 1 || line > len(lines) {
		return ""
	}
	srcLine := lines[line-1]
	if col < 1 {
		col = 1
	}
	caret := strings.Repeat(" ", col-1) + "^"
	return fmt.Sprintf("  %d | %s\n    | %s", line, srcLine, caret)
}

// TranspileFile transpiles a single .gox file into a .go file
func TranspileFile(goxPath string) error {
	content, err := os.ReadFile(goxPath)
	if err != nil {
		return err
	}

	transpiled, err := TranspileWithSource(string(content), goxPath)
	if err != nil {
		return err
	}

	outPath := strings.TrimSuffix(goxPath, ".gox") + ".go"
	header := "// Code generated by GoKS GOX compiler. DO NOT EDIT.\n"
	return os.WriteFile(outPath, []byte(header+transpiled), 0644)
}

// Transpile converts a .gox string to valid Go component syntax.
func Transpile(content string) (string, error) {
	return TranspileWithSource(content, "")
}

// TranspileWithSource converts a .gox string to valid Go component syntax,
// attaching file, line, column, and snippet diagnostics if a compilation error occurs.
func TranspileWithSource(content string, filename string) (string, error) {
	// Find all `return (` ... `)` blocks
	idx := 0
	for {
		start := strings.Index(content[idx:], "return (")
		if start == -1 {
			break
		}
		start += idx

		// Find matching parenthesis
		openCount := 1
		end := start + 8 // length of "return ("
		for end < len(content) {
			if content[end] == '(' {
				openCount++
			} else if content[end] == ')' {
				openCount--
				if openCount == 0 {
					break
				}
			}
			end++
		}

		if openCount != 0 || end >= len(content) {
			startLine := strings.Count(content[:start], "\n") + 1
			col := start - strings.LastIndex(content[:start], "\n")
			if strings.LastIndex(content[:start], "\n") == -1 {
				col = start + 1
			}
			return "", &CompileError{
				File:    filename,
				Line:    startLine,
				Column:  col,
				Snippet: createSnippet(content, startLine, col),
				Message: "unclosed 'return (' block: matching ')' not found",
			}
		}

		xmlContent := strings.TrimSpace(content[start+8 : end])

		// Parse XML
		transpiledXML, err := parseXMLToGo(xmlContent)
		if err != nil {
			lineInContent := strings.Count(content[:start+8], "\n") + 1
			colInContent := 1
			msg := err.Error()

			if xmlErr, ok := err.(*xml.SyntaxError); ok {
				lineInContent = strings.Count(content[:start+8], "\n") + xmlErr.Line
				msg = xmlErr.Msg
			}

			return "", &CompileError{
				File:    filename,
				Line:    lineInContent,
				Column:  colInContent,
				Snippet: createSnippet(content, lineInContent, colInContent),
				Message: fmt.Sprintf("failed to parse GOX markup: %s", msg),
			}
		}

		// Replace in content
		prefix := content[:start]
		suffix := content[end+1:]

		replacement := "return " + transpiledXML
		content = prefix + replacement + suffix
		idx = len(prefix) + len(replacement)
	}

	// Auto-inject html import if html package is used and not yet imported
	if strings.Contains(content, "html.") && !strings.Contains(content, `"github.com/misbakhul29/goks/pkg/html"`) {
		if strings.Contains(content, "import (") {
			content = strings.Replace(content, "import (", "import (\n\t\"github.com/misbakhul29/goks/pkg/html\"", 1)
		} else if strings.Contains(content, "package ") {
			if pkgIdx := strings.Index(content, "\n"); pkgIdx != -1 {
				content = content[:pkgIdx+1] + "\nimport \"github.com/misbakhul29/goks/pkg/html\"\n" + content[pkgIdx+1:]
			}
		}
	}

	// Auto-inject component import if component package is used and not yet imported
	if (strings.Contains(content, "component.") || strings.Contains(content, "Fragment(")) && !strings.Contains(content, `"github.com/misbakhul29/goks/pkg/component"`) {
		if strings.Contains(content, "import (") {
			content = strings.Replace(content, "import (", "import (\n\t\"github.com/misbakhul29/goks/pkg/component\"", 1)
		} else if strings.Contains(content, "package ") {
			if pkgIdx := strings.Index(content, "\n"); pkgIdx != -1 {
				content = content[:pkgIdx+1] + "\nimport \"github.com/misbakhul29/goks/pkg/component\"\n" + content[pkgIdx+1:]
			}
		}
	}

	return content, nil
}

// extractAttrExprs scans a GOX XML string for ={...} attribute expressions,
// replaces each with a safe placeholder (no quotes, no XML-special chars), and
// returns the substituted string along with a map of placeholder→original expr.
//
// This allows the XML decoder to parse GOX attributes that contain arbitrary Go
// expressions (e.g. string concatenation with `"`, function calls, etc.) without
// choking on unescaped quote characters.
func extractAttrExprs(xmlStr string) (string, map[string]string) {
	placeholders := make(map[string]string)
	var result strings.Builder
	i := 0
	count := 0

	for i < len(xmlStr) {
		if i+1 < len(xmlStr) && xmlStr[i] == '=' && xmlStr[i+1] == '{' {
			result.WriteByte('=') // keep the '='
			i++                   // skip '='

			// Collect balanced {…} expression (handles nesting and strings)
			depth := 0
			start := i
			var inQuote byte
			escaped := false

			for i < len(xmlStr) {
				ch := xmlStr[i]
				if inQuote != 0 {
					if escaped {
						escaped = false
					} else if ch == '\\' && inQuote != '`' {
						escaped = true
					} else if ch == inQuote {
						inQuote = 0
					}
				} else {
					if ch == '"' || ch == '\'' || ch == '`' {
						inQuote = ch
					} else if ch == '{' {
						depth++
					} else if ch == '}' {
						depth--
						if depth == 0 {
							i++
							break
						}
					}
				}
				i++
			}
			expr := xmlStr[start:i] // includes surrounding { }

			key := fmt.Sprintf("GOKSEXPR%d", count)
			count++
			placeholders[key] = expr
			// Write a safe, double-quoted placeholder the XML decoder can handle
			result.WriteString(`"` + key + `"`)
		} else {
			result.WriteByte(xmlStr[i])
			i++
		}
	}

	return result.String(), placeholders
}

func parseXMLToGo(xmlStr string) (string, error) {
	if xmlStr == "" {
		return "", nil
	}

	// Normalize shorthand fragments <> and </> to <Fragment> and </Fragment>
	xmlStr = strings.ReplaceAll(xmlStr, "<>", "<Fragment>")
	xmlStr = strings.ReplaceAll(xmlStr, "</>", "</Fragment>")

	// Pre-process: replace ={...} attribute expressions with safe placeholders
	// so the XML decoder doesn't trip over quotes or special chars inside {}.
	processed, placeholders := extractAttrExprs(xmlStr)

	d := xml.NewDecoder(strings.NewReader(processed))
	// Allow unescaped HTML characters and unknown entities
	d.Strict = false
	d.AutoClose = xml.HTMLAutoClose
	d.Entity = xml.HTMLEntity

	return parseNode(d, placeholders)
}

func parseNode(d *xml.Decoder, placeholders map[string]string) (string, error) {
	var children []string

	for {
		t, err := d.Token()
		if err != nil {
			if err.Error() == "EOF" {
				break
			}
			return "", err
		}

		switch token := t.(type) {
		case xml.Comment:
			// Safely ignore comments <!-- ... -->
			continue

		case xml.StartElement:
			tag := token.Name.Local

			// Extract namespace if any (e.g. c.Hero -> Space: c, Local: Hero)
			if token.Name.Space != "" {
				tag = token.Name.Space + "." + token.Name.Local
			}

			// Parse children recursively
			inner, err := parseNode(d, placeholders)
			if err != nil {
				return "", err
			}

			goCode := formatGoNode(tag, token.Attr, inner, placeholders)
			children = append(children, goCode)

		case xml.EndElement:
			return strings.Join(children, ", "), nil

		case xml.CharData:
			text := strings.TrimSpace(string(token))
			if text != "" {
				if strings.HasPrefix(text, "{") && strings.HasSuffix(text, "}") {
					expr := text[1 : len(text)-1]
					children = append(children, fmt.Sprintf("component.Any(%s)", expr))
				} else {
					children = append(children, fmt.Sprintf("%q", text))
				}
			}
		}
	}

	return strings.Join(children, ", "), nil
}

// resolveAttrVal checks whether val is a placeholder (from extractAttrExprs).
// If so, it returns (innerExpr, true) where innerExpr is the Go expression
// without surrounding braces. Otherwise it returns ("", false).
func resolveAttrVal(val string, placeholders map[string]string) (string, bool) {
	if expr, ok := placeholders[val]; ok {
		// expr is "{...}" — strip the outer braces
		return expr[1 : len(expr)-1], true
	}
	// Also handle the original {expr} syntax for text-content attributes
	// that weren't pre-processed (shouldn't happen after extractAttrExprs, kept for safety)
	if strings.HasPrefix(val, "{") && strings.HasSuffix(val, "}") {
		return val[1 : len(val)-1], true
	}
	return "", false
}

func formatGoNode(tag string, attrs []xml.Attr, inner string, placeholders map[string]string) string {
	isFragment := strings.EqualFold(tag, "Fragment")
	if isFragment {
		return fmt.Sprintf("component.Fragment(%s)", inner)
	}

	isComponent := strings.Contains(tag, ".")

	var goTag string
	if isComponent {
		goTag = tag // e.g. c.Hero
	} else {
		goTag = "html." + strings.ToUpper(tag[0:1]) + tag[1:]
	}

	var res string
	if isComponent {
		// Component instantiation: component.C(&c.Hero{Attr1: val, ...})
		// Deterministic prop ordering
		sort.Slice(attrs, func(i, j int) bool {
			return attrs[i].Name.Local < attrs[j].Name.Local
		})
		props := []string{}
		for _, a := range attrs {
			val := a.Value
			if expr, isDynamic := resolveAttrVal(val, placeholders); isDynamic {
				props = append(props, fmt.Sprintf("%s: %s", a.Name.Local, expr))
			} else {
				props = append(props, fmt.Sprintf("%s: %q", a.Name.Local, val))
			}
		}
		res = fmt.Sprintf("component.C(&%s{%s})", goTag, strings.Join(props, ", "))
	} else {
		// HTML element: html.Div(inner)
		res = fmt.Sprintf("%s(%s)", goTag, inner)

		// Deterministic attribute ordering
		sort.Slice(attrs, func(i, j int) bool {
			return attrs[i].Name.Local < attrs[j].Name.Local
		})

		for _, a := range attrs {
			name := a.Name.Local
			val := a.Value
			expr, isDynamic := resolveAttrVal(val, placeholders)

			if name == "class" {
				if isDynamic {
					res += fmt.Sprintf(`.Class(%s)`, expr)
				} else {
					res += fmt.Sprintf(`.Class(%q)`, val)
				}
			} else if name == "id" {
				if isDynamic {
					res += fmt.Sprintf(`.ID(%s)`, expr)
				} else {
					res += fmt.Sprintf(`.ID(%q)`, val)
				}
			} else if strings.HasPrefix(strings.ToLower(name), "on") && len(name) > 2 {
				if isDynamic {
					res += fmt.Sprintf(`.On(%q, %s)`, name, expr)
				} else {
					res += fmt.Sprintf(`.On(%q, %q)`, name, val)
				}
			} else {
				if isDynamic {
					res += fmt.Sprintf(`.Attr(%q, %s)`, name, expr)
				} else {
					res += fmt.Sprintf(`.Attr(%q, %q)`, name, val)
				}
			}
		}
	}

	return res
}

// NormalizeWorkspaceRel normalizes path segments for the .goks/workspace directory.
// Bracketed folder segments such as "[id]" and "[...slug]" are normalized to "_id" and "_slug"
// so that Go's compiler does not reject them as invalid import paths.
func NormalizeWorkspaceRel(rel string) string {
	parts := strings.Split(rel, string(filepath.Separator))
	for i, p := range parts {
		if strings.HasPrefix(p, "[...") && strings.HasSuffix(p, "]") {
			parts[i] = "_" + strings.TrimSuffix(strings.TrimPrefix(p, "[..."), "]")
		} else if strings.HasPrefix(p, "[") && strings.HasSuffix(p, "]") {
			parts[i] = "_" + strings.TrimSuffix(strings.TrimPrefix(p, "["), "]")
		}
	}
	return filepath.Join(parts...)
}
