package orm

import (
	"fmt"
	"reflect"
	"strings"
	"time"
)

// Create inserts a new model into the database.
// It sets ID, CreatedAt, and UpdatedAt via reflection.
func Create[T any](db *Database, m *T) error {
	if db == nil {
		db = DB
	}
	rv := reflect.ValueOf(m).Elem()
	rt := rv.Type()

	cols := []string{}
	placeholders := []string{}
	vals := []any{}
	n := 1

	now := time.Now()

	for i := 0; i < rt.NumField(); i++ {
		field := rt.Field(i)
		fv := rv.Field(i)

		// Skip embedded structs (e.g. orm.Model) by expanding them
		if field.Anonymous {
			for j := 0; j < fv.NumField(); j++ {
				subField := fv.Type().Field(j)
				subVal := fv.Field(j)
				col := dbTag(subField)
				if col == "id" {
					continue // auto-generated by DB
				}
				if col == "created_at" || col == "updated_at" {
					subVal.Set(reflect.ValueOf(now))
					cols = append(cols, col)
					placeholders = append(placeholders, db.dialect.Placeholder(n))
					vals = append(vals, now)
					n++
					continue
				}
				if col == "deleted_at" {
					continue // leave as NULL on create
				}
				if !subVal.CanInterface() {
					continue
				}
				cols = append(cols, col)
				placeholders = append(placeholders, db.dialect.Placeholder(n))
				vals = append(vals, subVal.Interface())
				n++
			}
			continue
		}

		col := dbTag(field)
		if col == "" || !fv.CanInterface() {
			continue
		}
		cols = append(cols, col)
		placeholders = append(placeholders, db.dialect.Placeholder(n))
		vals = append(vals, fv.Interface())
		n++
	}

	table := tableNameOf(m)
	query := fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES (%s) RETURNING id",
		table,
		strings.Join(cols, ", "),
		strings.Join(placeholders, ", "),
	)

	var id uint
	err := db.db.QueryRow(query, vals...).Scan(&id)
	if err != nil {
		return fmt.Errorf("goks/orm: Create: %w", err)
	}

	// Set the ID back on the model
	idField := rv.FieldByName("ID")
	if !idField.IsValid() {
		// Try embedded Model.ID
		modelField := rv.FieldByName("Model")
		if modelField.IsValid() {
			idField = modelField.FieldByName("ID")
		}
	}
	if idField.IsValid() && idField.CanSet() {
		idField.SetUint(uint64(id))
	}

	return nil
}

// Save inserts or updates a model based on whether its ID is set.
func Save[T any](db *Database, m *T) error {
	if db == nil {
		db = DB
	}
	rv := reflect.ValueOf(m).Elem()

	// Check if it has an ID
	idField := rv.FieldByName("ID")
	if !idField.IsValid() {
		modelField := rv.FieldByName("Model")
		if modelField.IsValid() {
			idField = modelField.FieldByName("ID")
		}
	}

	if idField.IsValid() && idField.Uint() == 0 {
		return Create(db, m)
	}
	return update(db, m)
}

// update performs a full UPDATE on an existing model.
func update[T any](db *Database, m *T) error {
	rv := reflect.ValueOf(m).Elem()
	rt := rv.Type()

	setParts := []string{}
	vals := []any{}
	n := 1
	var id uint
	now := time.Now()

	for i := 0; i < rt.NumField(); i++ {
		field := rt.Field(i)
		fv := rv.Field(i)
		if field.Anonymous {
			for j := 0; j < fv.NumField(); j++ {
				subField := fv.Type().Field(j)
				subVal := fv.Field(j)
				col := dbTag(subField)
				if col == "id" {
					id = uint(subVal.Uint())
					continue
				}
				if col == "created_at" || col == "deleted_at" {
					continue
				}
				if col == "updated_at" {
					subVal.Set(reflect.ValueOf(now))
					setParts = append(setParts, fmt.Sprintf("%s = %s", col, db.dialect.Placeholder(n)))
					vals = append(vals, now)
					n++
					continue
				}
				if !subVal.CanInterface() {
					continue
				}
				setParts = append(setParts, fmt.Sprintf("%s = %s", col, db.dialect.Placeholder(n)))
				vals = append(vals, subVal.Interface())
				n++
			}
			continue
		}
		col := dbTag(field)
		if col == "" || !fv.CanInterface() {
			continue
		}
		setParts = append(setParts, fmt.Sprintf("%s = %s", col, db.dialect.Placeholder(n)))
		vals = append(vals, fv.Interface())
		n++
	}

	vals = append(vals, id)
	table := tableNameOf(m)
	query := fmt.Sprintf(
		"UPDATE %s SET %s WHERE id = %s",
		table,
		strings.Join(setParts, ", "),
		db.dialect.Placeholder(n),
	)

	_, err := db.db.Exec(query, vals...)
	if err != nil {
		return fmt.Errorf("goks/orm: Save: %w", err)
	}
	return nil
}

// Delete performs a soft-delete by setting deleted_at to now.
func Delete[T any](db *Database, m *T) error {
	if db == nil {
		db = DB
	}
	rv := reflect.ValueOf(m).Elem()

	var id uint
	now := time.Now()

	// Find Model embedded struct
	modelField := rv.FieldByName("Model")
	if modelField.IsValid() {
		idVal := modelField.FieldByName("ID")
		if idVal.IsValid() {
			id = uint(idVal.Uint())
		}
		deletedAt := modelField.FieldByName("DeletedAt")
		if deletedAt.IsValid() && deletedAt.CanSet() {
			deletedAt.Set(reflect.ValueOf(&now))
		}
	}

	if id == 0 {
		return fmt.Errorf("goks/orm: Delete: model has no ID")
	}

	table := tableNameOf(m)
	query := fmt.Sprintf(
		"UPDATE %s SET deleted_at = %s WHERE id = %s",
		table,
		db.dialect.Placeholder(1),
		db.dialect.Placeholder(2),
	)
	_, err := db.db.Exec(query, now, id)
	if err != nil {
		return fmt.Errorf("goks/orm: Delete: %w", err)
	}
	return nil
}

// HardDelete permanently removes a record from the database.
func HardDelete[T any](db *Database, m *T) error {
	if db == nil {
		db = DB
	}
	rv := reflect.ValueOf(m).Elem()
	var id uint

	modelField := rv.FieldByName("Model")
	if modelField.IsValid() {
		idVal := modelField.FieldByName("ID")
		if idVal.IsValid() {
			id = uint(idVal.Uint())
		}
	}
	if id == 0 {
		return fmt.Errorf("goks/orm: HardDelete: model has no ID")
	}

	table := tableNameOf(m)
	query := fmt.Sprintf("DELETE FROM %s WHERE id = %s", table, db.dialect.Placeholder(1))
	_, err := db.db.Exec(query, id)
	if err != nil {
		return fmt.Errorf("goks/orm: HardDelete: %w", err)
	}
	return nil
}

// dbTag extracts the `db` struct tag value for a field.
func dbTag(f reflect.StructField) string {
	tag := f.Tag.Get("db")
	if tag == "" {
		return camelToSnake(f.Name)
	}
	return tag
}

// camelToSnake converts CamelCase to snake_case.
func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' && i > 0 {
			result.WriteByte('_')
		}
		result.WriteRune(r | 32) // toLower
	}
	return result.String()
}
