package orm

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"time"
)

// Create inserts a new model into the database using context.Background.
func Create[T any](db *Database, m *T) error {
	return CreateContext(context.Background(), db, m)
}

// CreateContext inserts a new model into the database with context.
// It triggers BeforeCreate and AfterCreate hooks if implemented by the model.
// It sets ID, CreatedAt, and UpdatedAt via reflection.
func CreateContext[T any](ctx context.Context, db *Database, m *T) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil {
		db = DB
	}
	if db == nil || db.db == nil {
		return fmt.Errorf("goks/orm: database connection not initialized")
	}
	dialect := db.dialect
	if dialect == nil {
		dialect = dialectFor("sqlite")
	}

	if err := invokeBeforeCreate(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: BeforeCreate: %w", err)
	}

	rv := reflect.ValueOf(m).Elem()
	rt := rv.Type()

	cols := []string{}
	placeholders := []string{}
	vals := []any{}
	n := 1

	now := time.Now()

	for i := 0; i < rt.NumField(); i++ {
		field := rt.Field(i)
		fv := rv.Field(i)

		// Skip embedded structs (e.g. orm.Model) by expanding them
		if field.Anonymous {
			for j := 0; j < fv.NumField(); j++ {
				subField := fv.Type().Field(j)
				subVal := fv.Field(j)
				col := dbTag(subField)
				if col == "id" {
					continue // auto-generated by DB
				}
				if col == "created_at" || col == "updated_at" {
					subVal.Set(reflect.ValueOf(now))
					cols = append(cols, col)
					placeholders = append(placeholders, dialect.Placeholder(n))
					vals = append(vals, now)
					n++
					continue
				}
				if col == "deleted_at" {
					continue // leave as NULL on create
				}
				if !subVal.CanInterface() {
					continue
				}
				cols = append(cols, col)
				placeholders = append(placeholders, dialect.Placeholder(n))
				vals = append(vals, subVal.Interface())
				n++
			}
			continue
		}

		col := dbTag(field)
		if col == "" || !fv.CanInterface() {
			continue
		}
		cols = append(cols, col)
		placeholders = append(placeholders, dialect.Placeholder(n))
		vals = append(vals, fv.Interface())
		n++
	}

	table := tableNameOf(m)
	if !isValidSQLIdentifier(table) {
		return fmt.Errorf("goks/orm: invalid table identifier: %s", table)
	}
	for _, col := range cols {
		if !isValidSQLIdentifier(col) {
			return fmt.Errorf("goks/orm: invalid column identifier: %s", col)
		}
	}
	var id uint

	if dialect != nil && dialect.SupportsReturning() {
		query := fmt.Sprintf(
			"INSERT INTO %s (%s) VALUES (%s) RETURNING id",
			table,
			strings.Join(cols, ", "),
			strings.Join(placeholders, ", "),
		)
		err := db.db.QueryRowContext(ctx, query, vals...).Scan(&id)
		if err != nil {
			return fmt.Errorf("goks/orm: Create: %w", err)
		}
	} else {
		query := fmt.Sprintf(
			"INSERT INTO %s (%s) VALUES (%s)",
			table,
			strings.Join(cols, ", "),
			strings.Join(placeholders, ", "),
		)
		res, err := db.db.ExecContext(ctx, query, vals...)
		if err != nil {
			return fmt.Errorf("goks/orm: Create: %w", err)
		}
		lastID, err := res.LastInsertId()
		if err == nil && lastID > 0 {
			id = uint(lastID)
		}
	}

	// Set the ID back on the model
	idField := rv.FieldByName("ID")
	if !idField.IsValid() {
		// Try embedded Model.ID
		modelField := rv.FieldByName("Model")
		if modelField.IsValid() {
			idField = modelField.FieldByName("ID")
		}
	}
	if idField.IsValid() && idField.CanSet() {
		idField.SetUint(uint64(id))
	}

	if err := invokeAfterCreate(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: AfterCreate: %w", err)
	}

	return nil
}

// Save inserts or updates a model based on whether its ID is set.
func Save[T any](db *Database, m *T) error {
	return SaveContext(context.Background(), db, m)
}

// SaveContext inserts or updates a model with context.
func SaveContext[T any](ctx context.Context, db *Database, m *T) error {
	if db == nil {
		db = DB
	}
	rv := reflect.ValueOf(m).Elem()

	// Check if it has an ID
	idField := rv.FieldByName("ID")
	if !idField.IsValid() {
		modelField := rv.FieldByName("Model")
		if modelField.IsValid() {
			idField = modelField.FieldByName("ID")
		}
	}

	if idField.IsValid() && idField.Uint() == 0 {
		return CreateContext(ctx, db, m)
	}
	return UpdateContext(ctx, db, m)
}

// Update updates an existing model in the database using context.Background.
func Update[T any](db *Database, m *T) error {
	return UpdateContext(context.Background(), db, m)
}

// UpdateContext updates an existing model in the database with context.
// It triggers BeforeUpdate and AfterUpdate hooks if implemented by the model.
func UpdateContext[T any](ctx context.Context, db *Database, m *T) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil || db.db == nil {
		return fmt.Errorf("goks/orm: database connection not initialized")
	}
	dialect := db.dialect
	if dialect == nil {
		dialect = dialectFor("sqlite")
	}

	if err := invokeBeforeUpdate(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: BeforeUpdate: %w", err)
	}

	rv := reflect.ValueOf(m).Elem()
	rt := rv.Type()

	setParts := []string{}
	vals := []any{}
	n := 1
	var id uint
	now := time.Now()

	for i := 0; i < rt.NumField(); i++ {
		field := rt.Field(i)
		fv := rv.Field(i)
		if field.Anonymous {
			for j := 0; j < fv.NumField(); j++ {
				subField := fv.Type().Field(j)
				subVal := fv.Field(j)
				col := dbTag(subField)
				if col == "id" {
					id = uint(subVal.Uint())
					continue
				}
				if col == "created_at" || col == "deleted_at" {
					continue
				}
				if col == "updated_at" {
					subVal.Set(reflect.ValueOf(now))
					setParts = append(setParts, fmt.Sprintf("%s = %s", col, dialect.Placeholder(n)))
					vals = append(vals, now)
					n++
					continue
				}
				if !subVal.CanInterface() {
					continue
				}
				setParts = append(setParts, fmt.Sprintf("%s = %s", col, dialect.Placeholder(n)))
				vals = append(vals, subVal.Interface())
				n++
			}
			continue
		}
		col := dbTag(field)
		if col == "" || !fv.CanInterface() {
			continue
		}
		setParts = append(setParts, fmt.Sprintf("%s = %s", col, dialect.Placeholder(n)))
		vals = append(vals, fv.Interface())
		n++
	}

	vals = append(vals, id)
	table := tableNameOf(m)
	query := fmt.Sprintf(
		"UPDATE %s SET %s WHERE id = %s",
		table,
		strings.Join(setParts, ", "),
		dialect.Placeholder(n),
	)

	_, err := db.db.ExecContext(ctx, query, vals...)
	if err != nil {
		return fmt.Errorf("goks/orm: Save: %w", err)
	}

	if err := invokeAfterUpdate(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: AfterUpdate: %w", err)
	}

	return nil
}

// Delete performs a soft-delete by setting deleted_at to now using context.Background.
func Delete[T any](db *Database, m *T) error {
	return DeleteContext(context.Background(), db, m)
}

// DeleteContext performs a soft-delete with context.
// It triggers BeforeDelete and AfterDelete hooks if implemented by the model.
func DeleteContext[T any](ctx context.Context, db *Database, m *T) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil {
		db = DB
	}
	if db == nil || db.db == nil {
		return fmt.Errorf("goks/orm: database connection not initialized")
	}
	dialect := db.dialect
	if dialect == nil {
		dialect = dialectFor("sqlite")
	}

	if err := invokeBeforeDelete(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: BeforeDelete: %w", err)
	}

	rv := reflect.ValueOf(m).Elem()

	var id uint
	now := time.Now()

	// Find Model embedded struct
	modelField := rv.FieldByName("Model")
	if modelField.IsValid() {
		idVal := modelField.FieldByName("ID")
		if idVal.IsValid() {
			id = uint(idVal.Uint())
		}
		deletedAt := modelField.FieldByName("DeletedAt")
		if deletedAt.IsValid() && deletedAt.CanSet() {
			deletedAt.Set(reflect.ValueOf(&now))
		}
	}

	if id == 0 {
		return fmt.Errorf("goks/orm: Delete: model has no ID")
	}

	table := tableNameOf(m)
	query := fmt.Sprintf(
		"UPDATE %s SET deleted_at = %s WHERE id = %s",
		table,
		dialect.Placeholder(1),
		dialect.Placeholder(2),
	)
	_, err := db.db.ExecContext(ctx, query, now, id)
	if err != nil {
		return fmt.Errorf("goks/orm: Delete: %w", err)
	}

	if err := invokeAfterDelete(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: AfterDelete: %w", err)
	}

	return nil
}

// HardDelete permanently removes a record from the database using context.Background.
func HardDelete[T any](db *Database, m *T) error {
	return HardDeleteContext(context.Background(), db, m)
}

// HardDeleteContext permanently removes a record from the database with context.
// It triggers BeforeDelete and AfterDelete hooks if implemented by the model.
func HardDeleteContext[T any](ctx context.Context, db *Database, m *T) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil {
		db = DB
	}
	if db == nil || db.db == nil {
		return fmt.Errorf("goks/orm: database connection not initialized")
	}
	dialect := db.dialect
	if dialect == nil {
		dialect = dialectFor("sqlite")
	}

	if err := invokeBeforeDelete(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: BeforeDelete: %w", err)
	}

	rv := reflect.ValueOf(m).Elem()
	var id uint

	modelField := rv.FieldByName("Model")
	if modelField.IsValid() {
		idVal := modelField.FieldByName("ID")
		if idVal.IsValid() {
			id = uint(idVal.Uint())
		}
	}
	if id == 0 {
		return fmt.Errorf("goks/orm: HardDelete: model has no ID")
	}

	table := tableNameOf(m)
	query := fmt.Sprintf("DELETE FROM %s WHERE id = %s", table, dialect.Placeholder(1))
	_, err := db.db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("goks/orm: HardDelete: %w", err)
	}

	if err := invokeAfterDelete(ctx, m); err != nil {
		return fmt.Errorf("goks/orm: AfterDelete: %w", err)
	}

	return nil
}

// Restore un-deletes a soft-deleted model by clearing deleted_at using context.Background.
func Restore[T any](db *Database, m *T) error {
	return RestoreContext(context.Background(), db, m)
}

// RestoreContext un-deletes a soft-deleted model by clearing deleted_at with context.
func RestoreContext[T any](ctx context.Context, db *Database, m *T) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil {
		db = DB
	}
	if db == nil || db.db == nil {
		return fmt.Errorf("goks/orm: database connection not initialized")
	}
	dialect := db.dialect
	if dialect == nil {
		dialect = dialectFor("sqlite")
	}

	rv := reflect.ValueOf(m).Elem()

	var id uint
	modelField := rv.FieldByName("Model")
	if modelField.IsValid() {
		idVal := modelField.FieldByName("ID")
		if idVal.IsValid() {
			id = uint(idVal.Uint())
		}
		deletedAt := modelField.FieldByName("DeletedAt")
		if deletedAt.IsValid() && deletedAt.CanSet() {
			deletedAt.Set(reflect.Zero(deletedAt.Type()))
		}
	}

	if id == 0 {
		return fmt.Errorf("goks/orm: Restore: model has no ID")
	}

	table := tableNameOf(m)
	if !isValidSQLIdentifier(table) {
		return fmt.Errorf("goks/orm: invalid table identifier: %s", table)
	}

	query := fmt.Sprintf("UPDATE %s SET deleted_at = NULL WHERE id = %s", table, dialect.Placeholder(1))
	_, err := db.db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("goks/orm: Restore: %w", err)
	}
	return nil
}

// FindByID retrieves a single model by its primary key ID using context.Background.
func FindByID[T any](db *Database, id any) (*T, error) {
	return FindByIDContext[T](context.Background(), db, id)
}

// FindByIDContext retrieves a single model by its primary key ID with context.
func FindByIDContext[T any](ctx context.Context, db *Database, id any) (*T, error) {
	return Query[T](db).WithContext(ctx).Where("id = ?", id).First()
}

// dbTag extracts the `db` struct tag value for a field.
func dbTag(f reflect.StructField) string {
	tag := f.Tag.Get("db")
	if tag == "-" {
		return ""
	}
	if tag == "" {
		return camelToSnake(f.Name)
	}
	return tag
}

// camelToSnake converts CamelCase to snake_case.
func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' && i > 0 {
			result.WriteByte('_')
		}
		result.WriteRune(r | 32) // toLower
	}
	return result.String()
}

func isValidSQLIdentifier(ident string) bool {
	if ident == "" || len(ident) > 64 {
		return false
	}
	for i, r := range ident {
		if i == 0 {
			if !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r == '_') {
				return false
			}
		} else {
			if !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_') {
				return false
			}
		}
	}
	return true
}
